version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - "8054:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    restart: on-failure
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  db:
    image: mysql:8
    ports:
      - "3308:3306"
    env_file:
      - .env
    restart: on-failure
    volumes:
      - ./my_db:/var/lib/mysql

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./client:/user/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf