# Generated by Django 4.1 on 2022-08-30 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_carsmodel_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carsmodel',
            name='body_type',
        ),
        migrations.RemoveField(
            model_name='carsmodel',
            name='engine',
        ),
        migrations.RemoveField(
            model_name='carsmodel',
            name='seats',
        ),
        migrations.AddField(
            model_name='carsmodel',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carsmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carsmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
