# Generated by Django 4.1 on 2022-09-01 15:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_parks', '0001_initial'),
        ('cars', '0003_remove_carsmodel_body_type_remove_carsmodel_engine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsmodel',
            name='year',
            field=models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2022)]),
        ),
        migrations.AlterField(
            model_name='carsmodel',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500000)]),
        ),
        migrations.AddField(
            model_name='carsmodel',
            name='auto_park',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='auto_parks.autoparkmodel'),
            preserve_default=False,
        ),
    ]
