# Generated by Django 4.1 on 2022-09-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carsmodel_auto_park_alter_carsmodel_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='cars'),
        ),
    ]
