# Generated by Django 4.1 on 2022-09-07 15:05

import django.core.validators
from django.db import migrations, models

import apps.users.services


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=apps.users.services.upload_to),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{2,100}', 'only letters min 2 max 100 characters')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^0[95687]{1}\\d{8}', 'Invalid phone number')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='surname',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{2,100}', 'only letters min 2 max 100 characters')]),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator('^(?=.*\\d)(?=.*[A-Z])(?=.*[a-z])(?=.*[^\\w\\s])([^\\s]){6,50}$', ['password must contain 1 number (0-9)', 'password must contain 1 uppercase letter', 'password must contain 1 lowercase letter', 'password must contain 1 non-alpha numeric', 'password is 6-50 characters without space'])]),
        ),
    ]
