# Generated by Django 4.1 on 2022-08-25 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carsmodel',
            table='cars',
        ),
    ]
